lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, friend_list, add_friend, validate_npm, delete_friend, all_friends

urlpatterns = [
        url(r'^$', index, name='index'),
        url(r'^add-friend/$', add_friend, name='add-friend'),
        url(r'^validate-npm/$', validate_npm, name='validate-npm'),
        url(r'^delete-friend/$', delete_friend, name='delete-friend'),
        url(r'^get-friend-list/$', friend_list, name='friend_list'),
        url(r'^all-friends/$', all_friends, name='all-friends' ),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$',RedirectView.as_view(url='/lab-4/', permanent='true'),name='index'),
	url(r'^admin/', admin.site.urls),
	url(r'^lab-1/', include(lab_1,namespace='lab-1')),
	url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4,namespace='lab-4')),
	url(r'^lab-5/', include(lab_5,namespace='lab-5')),
	url(r'^lab-6/', include(lab_6,namespace='lab-6')),
	url(r'^lab-7/', include(lab_7,namespace='lab-7')),
	url(r'^lab-8/', include(lab_8,namespace='lab-8')),
	url(r'^lab-9/', include(lab_9,namespace='lab-9')),
	url(r'^lab-10/', include(lab_10,namespace='lab-10')),
    #url(r'^$', index_lab1, name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_7/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
        friend_name = models.CharField(max_length=400)
        npm = models.CharField(max_length=250)
        added_at = models.DateField(auto_now_add=True)

class Mahasiswa(models.Model):
        mahasiswa_name = models.CharField(max_length=400)
        npm = models.CharField(max_length=250)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    paginator = Paginator(mahasiswa_list,20)
    friend_list = Friend.objects.all()

    page = request.GET.get('page')
    try:
        mahasiswa_list = paginator.page(page)
    except PageNotAnInteger:
        mahasiswa_list = paginator.page(1)
    except EmptyPage:
        mahasiswa_list = paginator.page(paginator.num_pages)

    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    response['author'] = "Fardhan Dhiadribratha Sudjono"
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    response['author'] = "Fardhan Dhiadribratha Sudjono"
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        is_taken = False
        friend_list = Friend.objects.all()
        for i in friend_list :
            if i.npm == npm :
                is_taken = True
        if not is_taken:
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return HttpResponse(data)
        else:
            return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        friend_id = request.POST['id']
        print(friend_id)
        Friend.objects.filter(id=friend_id).delete()
        data = { 'status' : 'ok'}
        return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    friend_list = Friend.objects.all()
    data = { 'is_taken' : False }
    for i in friend_list :
        if i.npm == npm :
            data = {
                'is_taken': True #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
            }
    return JsonResponse(data)

@csrf_exempt
def all_friends(request):
    friend_list = list(Friend.objects.all().values())
    data = {"json":friend_list}
    return JsonResponse(data)
    
def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Pacilfriends</h2>
                    <div id="friend-list" class="list-group">
                       
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
<script>
     var delFriend = function(id) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:delete-friend" %}',
            data: {id: id},
            success : function (friend) {
                $("#friend"+id).remove();
            },
            error : function (error) {
                alert("eRROR")
            }
        });
    };
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:all-friends" %}',
                success: function (response) {
                console.log(response);

                a = response.json;


                for (i in a) {
                    html = '<a class="list-group-item clearfix" id=friend'+a[i].id+' >' +a[i].friend_name+" ("+a[i].npm+')' +'<span class="glyphicon glyphicon-remove" onclick=delFriend('+a[i].id+') style="color: red;position: absolute;top: 8px;right: 16px;"></span>'+'</a>';
                $("#friend-list").append(html)
                }
                
                    
                },
                error: function(error){
                    //#tampilkan pesan error
                    alert("Data kosong");
                }
            });

            $('#friend_list').on('click', '.list-group-item .glyphicon', function() {
                $(this).closest('.list-group-item').remove();
                $.ajax({
                method: "GET",
                url: $(this).data('url'),
                success: function (response) {
                },
                error: function(error){
                    //#tampilkan pesan error
                    alert("Data kosong");
                }
            });
            });


        });
    </script>

{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                {% if mahasiswa_list.has_other_pages %}
                <ul class="pagination">
                  {% if mahasiswa_list.has_previous %}
                    <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a></li>
                  {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                  {% endif %}
                  {% for i in mahasiswa_list.paginator.page_range %}
                    {% if mahasiswa_list.number == i %}
                      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                      <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if mahasiswa_list.has_next %}
                    <li><a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a></li>
                  {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                  {% endif %}
                </ul>
              {% endif %}
              
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                    </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { name: nama, npm: npm},
            success : function (friend) {
                friend = JSON.parse(friend)
                console.log(friend.friend_name)
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name +" ("+ friend.npm+")"+
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                    $("#field_npm").val("")
                }
            }
        });
    });
</script>
{% endblock %}